export const ALFEEDLY_URL =
  "https://v2-api.sheety.co/28da54cb7e9da596d179cb63aae1b454/customers/feedback";

export const actionTypes = {
  POST_COMMENT: "POST_COMMENT",
  POST_COMMENT_SUCCESS: "POST_COMMENT_SUCCESS",
  POST_COMMENT_FAILURE: "POST_COMMENT_FAILURE",
  GET_COMMENTS: "GET_COMMENTS",
  GET_COMMENTS_FAILURE: "GET_COMMENTS_FAILURE",
  GET_COMMENTS_SUCCESS: "GET_COMMENTS_SUCCESS",
};
